# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [2]:
import numpy as np 

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [31]:
# 1-dimensional numpy array
d1_np = np.array([1, 2, 3])
print('1-Dimensional numpy array:\n', d1_np, '\n')

# 2-dimensional numpy array
d2_np = np.array([[1, 2, 3], [4, 5, 6]])
print('2-Dimensional numpy array:\n', d2_np, '\n')

# 3-dimensional numpy array
d3_np = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [5, 3, 9]]])
print('3-Dimensional numpy array:\n', d3_np, '\n')


1-Dimensional numpy array:
 [1 2 3] 

2-Dimensional numpy array:
 [[1 2 3]
 [4 5 6]] 

3-Dimensional numpy array:
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [5 3 9]]] 



## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [38]:
my_array = np.array([[3, 5, 7],
                    [6, 9, 4],
                    [9, 7, 5],
                    [4, 8, 7]])

# Display the dimension number of an array
print(my_array.ndim)

# Display the shape of an array
print(my_array.shape)

# Display the size of an array
print(my_array.size)

# Display the type of an array
print(my_array.dtype)

# Display the ength of an array element in bytes.
print(my_array.itemsize)

# Display the Python buffer object pointing to the start of the array’s data
print(my_array.data)

# Display total bytes consumed by the elements of the array.
print(my_array.nbytes)

2
(4, 3)
12
int32
4
48


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [34]:
# Create an array filled with ones
one_array = np.ones(3, dtype=int)
print(one_array)

# Create an array filled with zeros
zero_array = np.zeros(3, dtype=int)
print(zero_array)

# Create an array without initializing entries
empty_array = np.empty((2, 2), dtype=int)
print(empty_array)

# Create an array filled with sevens
full_array = np.full((3, 3), 7)
print(full_array)

# Create an evenly spaced values array within a given interval
arange_array = np.arange(2, 18, 3)
print(arange_array)

# Create an evenly spaced numbers array over a specified interval
line_array = np.linspace(4, 20, num=5, dtype=int)
print(line_array)

# Crear an array with random nu,ber between 0-1
random_array = np.random.random(5)
print(random_array)

[1 1 1]
[0 0 0]
[[0 1]
 [2 3]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[ 2  5  8 11 14 17]
[ 4  8 12 16 20]
[0.98333847 0.9368752  0.31912117 0.749152   0.50693391]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [59]:
ar1 = np.random.random((3, 2))
ar2 = np.ones((4, 1, 2))
print(f"first array shape: {ar1.shape}")
print(ar1,'\n')
print(f"second array shape: {ar2.shape}")
print(ar2, '\n')

# Addition
add = ar1 + ar2
print('Addition:\n', add, '\n')

# Multiplication
mul = ar1*ar2
print('Multiplication:\n', mul,'\n')

# Subtraction
sub = ar1 - ar2
print('Subtraction:\n', sub)

first array shape: (3, 2)
[[0.32003215 0.25160732]
 [0.87743018 0.3016261 ]
 [0.92789694 0.25204649]] 

second array shape: (4, 1, 2)
[[[1. 1.]]

 [[1. 1.]]

 [[1. 1.]]

 [[1. 1.]]] 

Addition:
 [[[1.32003215 1.25160732]
  [1.87743018 1.3016261 ]
  [1.92789694 1.25204649]]

 [[1.32003215 1.25160732]
  [1.87743018 1.3016261 ]
  [1.92789694 1.25204649]]

 [[1.32003215 1.25160732]
  [1.87743018 1.3016261 ]
  [1.92789694 1.25204649]]

 [[1.32003215 1.25160732]
  [1.87743018 1.3016261 ]
  [1.92789694 1.25204649]]] 

Multiplication:
 [[[0.32003215 0.25160732]
  [0.87743018 0.3016261 ]
  [0.92789694 0.25204649]]

 [[0.32003215 0.25160732]
  [0.87743018 0.3016261 ]
  [0.92789694 0.25204649]]

 [[0.32003215 0.25160732]
  [0.87743018 0.3016261 ]
  [0.92789694 0.25204649]]

 [[0.32003215 0.25160732]
  [0.87743018 0.3016261 ]
  [0.92789694 0.25204649]]] 

Subtraction:
 [[[-0.67996785 -0.74839268]
  [-0.12256982 -0.6983739 ]
  [-0.07210306 -0.74795351]]

 [[-0.67996785 -0.74839268]
  [-0.12256982 -

In [60]:
ar1 = np.random.random((3, 2))
ar2 = np.ones((4, 2, 2))
print(f"first array shape: {ar1.shape}")
print(ar1,'\n')
print(f"second array shape: {ar2.shape}")
print(ar2, '\n')

# Addition
add = ar1 + ar2
print('Addition:\n', add, '\n')

# Multiplication
mul = ar1*ar2
print('Multiplication:\n', mul,'\n')

# Subtraction
sub = ar1 - ar2
print('Subtraction:\n', sub)

first array shape: (3, 2)
[[0.24012489 0.93724268]
 [0.58392825 0.13045322]
 [0.96343855 0.52011976]] 

second array shape: (4, 2, 2)
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]] 



ValueError: operands could not be broadcast together with shapes (3,2) (4,2,2) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [86]:
ar1 = np.arange(2, 32, 2)
print(ar1)

ar2 = np.linspace(3, 50, num=15, dtype=int)
print(ar2)

ar3 = np.random.random(5)
print(ar3)

# Find the summary value in an array
sum_value = ar2.sum()
print('Summary_Second array:', sum_value)

# Find the minimum value in an aray
min_value = ar3.min()
print('Minimum_Third array:', min_value)

# Find cumulative sum of the elements along a given axis
cumsum_value = ar3.cumsum()
print('Cumulative summary_Third array:', cumsum_value)

# Find the mean value in an array
min_value = ar1.min()
print('Mean_First array:', min_value)

# Find correlation of arrays
corr = np.corrcoef(ar1, ar2)
print('Correlation_First and Second array:\n', corr)

# Find standard deviation 
std = np.std(ar3)
print('Standard deviation_Third array:', std)

# Find the variance
var = np.var(ar1)
print('Variance_First array', var)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 3  6  9 13 16 19 23 26 29 33 36 39 43 46 50]
[0.18783869 0.73891517 0.18034056 0.32108739 0.74864496]
Summary_Second array: 391
Minimum_Third array: 0.18034055654042924
Cumulative summary_Third array: [0.18783869 0.92675386 1.10709442 1.42818181 2.17682678]
Mean_First array: 2
Correlation_First and Second array:
 [[1.         0.99978803]
 [0.99978803 1.        ]]
Standard deviation_Third array: 0.256769607222188
Variation_First array 74.66666666666667


## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [93]:
ar1 = [True, False, True, False, False, True]
ar2 = [False, True, True, False, True, True]

# Execute the "and" logic
and_logic = np.logical_and(ar1, ar2)
print('and logical:', or_logic)

# Execute tjhe "or logic"
or_logic = np.logical_or(ar1, ar2)
print('or logical:', or_logic)

# Execute the "not" logic
not_logic = np.logical_not(ar2)
print('not logical:', not_logic)

and logical: [ True  True  True False  True  True]
or logical: [ True  True  True False  True  True]
not logical: [ True False False  True False False]
